interface ZIF_C_ATS_XX_FLIGHT_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_ATS_XX_FLIGHT,
 ACTIVATION                     TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4D4B6B',
 AO_APPROVE                     TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EDEB1955920D938C408',
 CREATE_ZC_ATS_XX_FLIGHT        TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA82B68',
 DELETE_ZC_ATS_XX_FLIGHT        TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA8AB68',
 EDIT                           TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4D2B6B',
 LOCK_ZC_ATS_XX_FLIGHT          TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA76B68',
 PREPARATION                    TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4D8B6B',
 SAVE_ZC_ATS_XX_FLIGHT          TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA92B68',
 UNLOCK_ZC_ATS_XX_FLIGHT        TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA7AB68',
 UPDATE_ZC_ATS_XX_FLIGHT        TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA86B68',
 VALIDATE_ZC_ATS_XX_FLIGHT      TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA8EB68',
 VALIDATION                     TYPE /BOBF/ACT_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4D6B6B',
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_ATS_XX_FLIGHT,
        BEGIN OF EDIT,
 PRESERVE_CHANGES               TYPE STRING VALUE 'PRESERVE_CHANGES',
        END OF EDIT,
        BEGIN OF LOCK_ZC_ATS_XX_FLIGHT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ZC_ATS_XX_FLIGHT,
        BEGIN OF PREPARATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF PREPARATION,
        BEGIN OF UNLOCK_ZC_ATS_XX_FLIGHT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ZC_ATS_XX_FLIGHT,
        BEGIN OF VALIDATION,
 SIDEEFFECTSQUALIFIER           TYPE STRING VALUE 'SIDEEFFECTSQUALIFIER',
        END OF VALIDATION,
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_ATS_XX_FLIGHT,
 ACTIVE_ENTITY_KEY              TYPE /BOBF/OBM_ALTKEY_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4D0B6B',
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_ATS_XX_FLIGHT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA74B68',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA70B68',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA80B68',
      END OF ZC_ATS_XX_FLIGHT,
      BEGIN OF ZC_ATS_XX_FLIGHT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA98B68',
      END OF ZC_ATS_XX_FLIGHT_LOCK,
      BEGIN OF ZC_ATS_XX_FLIGHT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA96B68',
      END OF ZC_ATS_XX_FLIGHT_MESSAGE,
      BEGIN OF ZC_ATS_XX_FLIGHT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA9AB68',
      END OF ZC_ATS_XX_FLIGHT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_ATS_XX_FLIGHT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA66B68' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_ATS_XX_FLIGHT' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZC_ATS_XX_FLIGHT,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4DAB6B',
 CALC_SEAT_XX                   TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EDEB1950D035B372249',
 CENTRAL_ADMIN_DATA             TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4DCB6B',
 DELETE_DRAFT_WHN_ACTIVE_DELETE TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4EAB6B',
 DRAFT_ACTION_CONTROL           TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4E8B6B',
 DRAFT_SYS_ADMIN_DATA           TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4E6B6B',
 DURABLE_LOCK_CLEANUP_CLEANUP   TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4E4B6B',
 DURABLE_LOCK_CLEANUP_DELETE    TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4DEB6B',
 DURABLE_LOCK_CLEANUP_FAIL_SAVE TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4E2B6B',
 DURABLE_LOCK_CLEANUP_SUCC_SAVE TYPE /BOBF/DET_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4E0B6B',
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 DRAFT_CONSISTENCY              TYPE /BOBF/OBM_GROUP_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA9EB68',
 ZC_ATS_XX_FLIGHT               TYPE /BOBF/OBM_GROUP_KEY VALUE '15C3CA10B0E61EEEB19438929F2E1D80',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_ATS_XX_FLIGHT               TYPE /BOBF/OBM_NODE_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA6AB68',
 ZC_ATS_XX_FLIGHT_LOCK          TYPE /BOBF/OBM_NODE_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA72B68',
 ZC_ATS_XX_FLIGHT_MESSAGE       TYPE /BOBF/OBM_NODE_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA6EB68',
 ZC_ATS_XX_FLIGHT_PROPERTY      TYPE /BOBF/OBM_NODE_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA7EB68',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_ATS_XX_FLIGHT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  CARRID                         TYPE STRING VALUE 'CARRID',
  CONNID                         TYPE STRING VALUE 'CONNID',
  MEAL                           TYPE STRING VALUE 'MEAL',
  TOTAL_SEATS                    TYPE STRING VALUE 'TOTAL_SEATS',
  STATUS                         TYPE STRING VALUE 'STATUS',
  ACTIVEUUID                     TYPE STRING VALUE 'ACTIVEUUID',
  HASACTIVEENTITY                TYPE STRING VALUE 'HASACTIVEENTITY',
  DRAFTENTITYCREATIONDATETIME    TYPE STRING VALUE 'DRAFTENTITYCREATIONDATETIME',
  DRAFTENTITYLASTCHANGEDATETIME  TYPE STRING VALUE 'DRAFTENTITYLASTCHANGEDATETIME',
  DRAFTADMINISTRATIVEDATAUUID    TYPE STRING VALUE 'DRAFTADMINISTRATIVEDATAUUID',
  DRAFTENTITYCONSISTENCYSTATUS   TYPE STRING VALUE 'DRAFTENTITYCONSISTENCYSTATUS',
  DRAFTENTITYOPERATIONCODE       TYPE STRING VALUE 'DRAFTENTITYOPERATIONCODE',
  ISACTIVEENTITY                 TYPE STRING VALUE 'ISACTIVEENTITY',
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_ATS_XX_FLIGHT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA6CB68',
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_STATUS_VARIABLE,
      BEGIN OF ZC_ATS_XX_FLIGHT,
 DRAFT_CONSISTENCY_STATUS       TYPE /BOBF/STA_VAR_KEY VALUE '15C3CA10B0E61EEEB0FE8C438DA9CB68',
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_STATUS_VARIABLE .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZC_ATS_XX_FLIGHT,
 CHECK_CARRID                   TYPE /BOBF/VAL_KEY VALUE '15C3CA10B0E61EEEB19438929F2DBD80',
 DURABLE_LOCK_CREATE_FOR_NEW    TYPE /BOBF/VAL_KEY VALUE '15C3CA10B0E61EEEB0FE8C9DEE4ECB6B',
      END OF ZC_ATS_XX_FLIGHT,
    END OF SC_VALIDATION .
endinterface.
